"""
Generate v11 2025-only blueprint + training-config variants for the HPO campaign.

For each (airline, direction, pos_frac) tuple, emits:
  - data/blueprint_{dir}_{AIR}_v11_2025_pf{PF}.json
  - data/{dir}_train_{AIR}_100_v11_2025_pf{PF}.json

Key rewrites vs the production v11 configs:
  - start_date / end_date -> 2025-01-01 / 2025-12-31
  - input_flights_path    -> Year=2025 only
  - history_flights_path  -> Year=2024/Month=10..12 warmup + Year=2025
  - feature_balance.pos_frac -> the requested pos_frac
  - balance.pos_frac         -> the requested pos_frac (mirrors feature_balance)
  - Unbalanced-features paths: v11 -> v11_2025 (pos_frac-independent, shared across variants
    so a single feature-gen pass serves all 3 pos_frac blueprints)
  - Balanced-training paths:   v11 -> v11_2025_pf{PF} (distinct per pos_frac)
  - Output dir & deploy joblib: v11 -> v11_2025_pf{PF}

Usage:
  python scripts/smoke/generate_v11_2025_configs.py \\
      --airlines WN,AA,DL,UA \\
      --directions dep,arr \\
      --pos-fracs 0.3,0.4,0.5

All paths are resolved relative to the repo root; run from repo root.
"""
from __future__ import annotations

import argparse
import copy
import json
import re
from pathlib import Path
from typing import Iterable

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data"

START_DATE = "2025-01-01"
END_DATE = "2025-12-31"

INPUT_GLOBS = [
    "../flightrightdata/data/raw_bts/Year=2025/Month=*/flights.parquet",
]
# Warmup: Oct-Dec 2024 covers the 60-day history_lookback_days at 2025-01-01.
HISTORY_GLOBS = [
    "../flightrightdata/data/raw_bts/Year=2024/Month=1[0-2]/flights.parquet",
    "../flightrightdata/data/raw_bts/Year=2025/Month=*/flights.parquet",
]


def _pf_tag(pos_frac: float) -> str:
    """Format pos_frac as a zero-padded 3-digit tag, e.g. 0.4 -> '040', 0.3 -> '030'."""
    return f"{int(round(pos_frac * 100)):03d}"


def _rewrite_paths(s: str, pf_tag: str, balanced: bool) -> str:
    """Rewrite v11 path tokens to v11_2025 (or v11_2025_pf{PF} for balanced-only tokens).

    - `balanced=False`: unbalanced features paths — `v11` -> `v11_2025` only
    - `balanced=True`:  balanced-training paths or output dir — `v11` -> `v11_2025_pf{PF}`

    Matches `v11` as a version token: not preceded by a digit or letter and not
    followed by another digit (so `v11` in `v111` or `xv11` is left alone, but
    `v11`, `v11_unbalanced`, `v11.parquet`, `v11_eval` all match).
    """
    target_tag = f"v11_2025_pf{pf_tag}" if balanced else "v11_2025"
    return re.sub(r"(?<![A-Za-z0-9])v11(?!\d)", target_tag, s)


def _recursive_rewrite(
    obj,
    pf_tag: str,
    balanced_keys: frozenset[str],
    in_balanced: bool = False,
):
    """Walk a JSON-ish structure and rewrite path strings in place.

    `balanced_keys` are keys whose values (and recursively their contents) should use
    the `v11_2025_pf{PF}` naming. Everything else uses `v11_2025`.
    """
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            sub_balanced = in_balanced or (k in balanced_keys)
            out[k] = _recursive_rewrite(v, pf_tag, balanced_keys, sub_balanced)
        return out
    if isinstance(obj, list):
        return [_recursive_rewrite(x, pf_tag, balanced_keys, in_balanced) for x in obj]
    if isinstance(obj, str):
        return _rewrite_paths(obj, pf_tag, in_balanced)
    return obj


# Blueprint keys whose values point at balanced-training outputs (get pf{PF} suffix).
BLUEPRINT_BALANCED_KEYS = frozenset({
    "output_template",  # feature_balance.output_template -> train_{dir}_ge{thr}_balanced_{AIR}_v11_2025_pf{PF}.parquet
})

# Training-config keys whose values get pf{PF} suffix.
TRAIN_BALANCED_KEYS = frozenset({
    "per_threshold_train_paths",
    "outdir",
    "deploy_bundle_joblib_name",
    "eval_output_parquet_name",
    "metrics_output_json_name",
    "output_template",  # nested feature_balance.output_template if present
})


def _bump_comment(cfg: dict, year_mode_tag: str, pos_frac: float) -> None:
    c = cfg.get("_comment", "")
    note = (
        f" [v11_2025_pf{_pf_tag(pos_frac)}: data scope {year_mode_tag}, "
        f"feature_balance.pos_frac={pos_frac}. Generated by "
        "scripts/smoke/generate_v11_2025_configs.py for the v11 2025-only HPO campaign.]"
    )
    if note.strip() in c:
        return
    cfg["_comment"] = c + note


def _set_pos_frac(cfg: dict, pos_frac: float) -> None:
    """Set pos_frac in both `balance` and `feature_balance` sections if present."""
    for section_key in ("balance", "feature_balance"):
        section = cfg.get(section_key)
        if isinstance(section, dict) and "pos_frac" in section:
            section["pos_frac"] = pos_frac


def _set_date_and_globs(cfg: dict) -> None:
    cfg["start_date"] = START_DATE
    cfg["end_date"] = END_DATE
    if "input_flights_path" in cfg:
        cfg["input_flights_path"] = list(INPUT_GLOBS)
    if "history_flights_path" in cfg:
        cfg["history_flights_path"] = list(HISTORY_GLOBS)


def generate_dep_blueprint(
    src: Path, airline: str, pos_frac: float, out_dir: Path
) -> Path:
    cfg = json.loads(src.read_text())
    pf_tag = _pf_tag(pos_frac)

    # Rewrite all string paths.
    cfg = _recursive_rewrite(cfg, pf_tag, BLUEPRINT_BALANCED_KEYS)

    # Overwrite date range + globs (they were rewritten above, but we now set them fresh).
    _set_date_and_globs(cfg)
    _set_pos_frac(cfg, pos_frac)
    _bump_comment(cfg, "2025-only", pos_frac)

    out_path = out_dir / f"blueprint_dep_{airline}_v11_2025_pf{pf_tag}.json"
    out_path.write_text(json.dumps(cfg, indent=2) + "\n")
    return out_path


def generate_arr_blueprint(
    src: Path, airline: str, pos_frac: float, out_dir: Path
) -> Path:
    cfg = json.loads(src.read_text())
    pf_tag = _pf_tag(pos_frac)

    cfg = _recursive_rewrite(cfg, pf_tag, BLUEPRINT_BALANCED_KEYS)
    # arr blueprints have start/end but no flight globs (they read dep intermediates).
    cfg["start_date"] = START_DATE
    cfg["end_date"] = END_DATE
    _set_pos_frac(cfg, pos_frac)
    _bump_comment(cfg, "2025-only", pos_frac)

    out_path = out_dir / f"blueprint_arr_{airline}_v11_2025_pf{pf_tag}.json"
    out_path.write_text(json.dumps(cfg, indent=2) + "\n")
    return out_path


def generate_train_config(
    src: Path, airline: str, direction: str, pos_frac: float, out_dir: Path
) -> Path:
    cfg = json.loads(src.read_text())
    pf_tag = _pf_tag(pos_frac)

    cfg = _recursive_rewrite(cfg, pf_tag, TRAIN_BALANCED_KEYS)
    _bump_comment(cfg, "2025-only", pos_frac)

    out_path = out_dir / f"{direction}_train_{airline}_100_v11_2025_pf{pf_tag}.json"
    out_path.write_text(json.dumps(cfg, indent=2) + "\n")
    return out_path


def _parse_list(s: str) -> list[str]:
    return [x.strip() for x in s.split(",") if x.strip()]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--airlines", default="WN,AA,DL,UA", help="Comma-separated airline codes.")
    ap.add_argument("--directions", default="dep,arr", help="Comma-separated: dep,arr.")
    ap.add_argument(
        "--pos-fracs",
        default="0.3,0.4,0.5",
        help="Comma-separated positive fractions to generate (e.g. 0.3,0.4,0.5).",
    )
    args = ap.parse_args()

    airlines = _parse_list(args.airlines)
    directions = _parse_list(args.directions)
    pos_fracs = [float(x) for x in _parse_list(args.pos_fracs)]

    for pf in pos_fracs:
        if not (0.0 < pf < 1.0):
            raise SystemExit(f"pos_frac must be in (0, 1), got {pf}")

    for direction in directions:
        if direction not in ("dep", "arr"):
            raise SystemExit(f"direction must be 'dep' or 'arr', got {direction!r}")

    for airline in airlines:
        for direction in directions:
            blueprint_src = DATA / f"blueprint_{direction}_{airline}_v11.json"
            train_src = DATA / f"{direction}_train_{airline}_100_v11.json"
            if not blueprint_src.exists():
                raise SystemExit(f"Missing source blueprint: {blueprint_src}")
            if not train_src.exists():
                raise SystemExit(f"Missing source training config: {train_src}")

            for pf in pos_fracs:
                if direction == "dep":
                    bp_out = generate_dep_blueprint(blueprint_src, airline, pf, DATA)
                else:
                    bp_out = generate_arr_blueprint(blueprint_src, airline, pf, DATA)
                train_out = generate_train_config(train_src, airline, direction, pf, DATA)
                print(f"[OK] {airline} {direction} pf={pf} -> {bp_out.name}, {train_out.name}")


if __name__ == "__main__":
    main()
